# Generated by Django 4.1.7 on 2023-03-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=10)),
                ("Chinese", models.CharField(max_length=10)),
                ("Math", models.CharField(max_length=10)),
                ("English", models.CharField(max_length=10)),
                ("Chemistry", models.CharField(max_length=10)),
                ("Biology", models.CharField(max_length=10)),
                ("Physics", models.CharField(max_length=10)),
                ("All_score", models.CharField(max_length=10)),
            ],
        ),
    ]
