# Generated by Django 4.1.7 on 2023-04-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Table",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=15)),
                ("Password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
